//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmxReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AsmxReference.AndrWebServiceSoap")]
    public interface AndrWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> RegisterAsync(string fname, string lname, string ph, string mail, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<AsmxReference.Result> LoginAsync(string uname, string pass, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SpecialistRegister", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string> SpecialistRegisterAsync(string fname, string lname, string ph, string center, string mail, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string> AddStudentAsync(string fname, string lname, string gender, string pemail, System.DateTime dob, string cntr, string spFname, string spLname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminRegiser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string> AdminRegiserAsync(string name, string email, string password, string center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveGameState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<AsmxReference.Result> SaveGameStateAsync(string fn, string ln, string lvlid, int scr, System.DateTime t, int atmp, string parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCenters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string[]> GetCentersAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUnConfirmedSpec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string[]> GetUnConfirmedSpecAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string[]> GetStudentsAsync(string email, string role, bool conf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string[]> GetCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLvls", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string[]> GetLvlsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpecialists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string[]> GetSpecialistsAsync(string center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminSpecialists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string[]> AdminSpecialistsAsync(string email, bool conf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<AsmxReference.Result> DeleteStudentAsync(string fname, string lname, string parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParentEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string> GetParentEmailAsync(int id, string specEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAdminEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string> GetAdminEmailAsync(string center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParentNum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string> GetParentNumAsync(int id, string specEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string> GetPassAsync(string email, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmailIsExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<AsmxReference.Result> EmailIsExistsAsync(string email, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<AsmxReference.GameState> GetStudentInfoAsync(int id, string specialist, string lvl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStudentfname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<AsmxReference.Result> UpdateStudentfnameAsync(int id, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStudentLname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<AsmxReference.Result> UpdateStudentLnameAsync(int id, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandomString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<AsmxReference.Result> RandomStringAsync(int length, string center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<AsmxReference.Result> ConfirmStudentAsync(int id, bool conf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmSpecialist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<AsmxReference.Result> ConfirmSpecialistAsync(string email, bool conf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminStudentInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<AsmxReference.Student> AdminStudentInfoAsync(int id, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminSpecialisttInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<AsmxReference.Specialist> AdminSpecialisttInfoAsync(string email, string fn, string ln);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string> GetFirstnameAsync(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Center))]
        System.Threading.Tasks.Task<string> GetLastNameAsync(string item);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result
    {
        
        private string errorField;
        
        private bool isValidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsValid
        {
            get
            {
                return this.isValidField;
            }
            set
            {
                this.isValidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Parent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Specialist))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Student))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Level))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GameState))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Center
    {
        
        private string center_nameField;
        
        private string city_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Center_name
        {
            get
            {
                return this.center_nameField;
            }
            set
            {
                this.center_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City_name
        {
            get
            {
                return this.city_nameField;
            }
            set
            {
                this.city_nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Specialist))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Student))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Level))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GameState))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Parent : Center
    {
        
        private string first_nameField;
        
        private string last_nameField;
        
        private string parentPhoneField;
        
        private string parentEmailField;
        
        private string parentPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string First_name
        {
            get
            {
                return this.first_nameField;
            }
            set
            {
                this.first_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Last_name
        {
            get
            {
                return this.last_nameField;
            }
            set
            {
                this.last_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ParentPhone
        {
            get
            {
                return this.parentPhoneField;
            }
            set
            {
                this.parentPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ParentEmail
        {
            get
            {
                return this.parentEmailField;
            }
            set
            {
                this.parentEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ParentPassword
        {
            get
            {
                return this.parentPasswordField;
            }
            set
            {
                this.parentPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Specialist : Parent
    {
        
        private string spFirst_nameField;
        
        private string spLast_nameField;
        
        private string spPhoneField;
        
        private string spEmailField;
        
        private string spResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SpFirst_name
        {
            get
            {
                return this.spFirst_nameField;
            }
            set
            {
                this.spFirst_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SpLast_name
        {
            get
            {
                return this.spLast_nameField;
            }
            set
            {
                this.spLast_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SpPhone
        {
            get
            {
                return this.spPhoneField;
            }
            set
            {
                this.spPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SpEmail
        {
            get
            {
                return this.spEmailField;
            }
            set
            {
                this.spEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SpResult
        {
            get
            {
                return this.spResultField;
            }
            set
            {
                this.spResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Level))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GameState))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Student : Parent
    {
        
        private int idField;
        
        private string studntFirst_nameField;
        
        private string studntLast_nameField;
        
        private string genderField;
        
        private System.DateTime dOBField;
        
        private int ageField;
        
        private string parent1Field;
        
        private string resultField;
        
        private string specialistField;
        
        private string specialistNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StudntFirst_name
        {
            get
            {
                return this.studntFirst_nameField;
            }
            set
            {
                this.studntFirst_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StudntLast_name
        {
            get
            {
                return this.studntLast_nameField;
            }
            set
            {
                this.studntLast_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DOB
        {
            get
            {
                return this.dOBField;
            }
            set
            {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Age
        {
            get
            {
                return this.ageField;
            }
            set
            {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parent", Order=6)]
        public string Parent1
        {
            get
            {
                return this.parent1Field;
            }
            set
            {
                this.parent1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Specialist
        {
            get
            {
                return this.specialistField;
            }
            set
            {
                this.specialistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SpecialistName
        {
            get
            {
                return this.specialistNameField;
            }
            set
            {
                this.specialistNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GameState))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Level : Student
    {
        
        private string level_IDField;
        
        private int gradeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Level_ID
        {
            get
            {
                return this.level_IDField;
            }
            set
            {
                this.level_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GameState : Level
    {
        
        private string fnameField;
        
        private string lnameField;
        
        private int stud_IDField;
        
        private string lvl_IDField;
        
        private int scoreField;
        
        private int attemptsField;
        
        private System.DateTime timeField;
        
        private bool stateField;
        
        private string gameErrResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Fname
        {
            get
            {
                return this.fnameField;
            }
            set
            {
                this.fnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Lname
        {
            get
            {
                return this.lnameField;
            }
            set
            {
                this.lnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Stud_ID
        {
            get
            {
                return this.stud_IDField;
            }
            set
            {
                this.stud_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Lvl_ID
        {
            get
            {
                return this.lvl_IDField;
            }
            set
            {
                this.lvl_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Score
        {
            get
            {
                return this.scoreField;
            }
            set
            {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Attempts
        {
            get
            {
                return this.attemptsField;
            }
            set
            {
                this.attemptsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime Time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string GameErrResult
        {
            get
            {
                return this.gameErrResultField;
            }
            set
            {
                this.gameErrResultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface AndrWebServiceSoapChannel : AsmxReference.AndrWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class AndrWebServiceSoapClient : System.ServiceModel.ClientBase<AsmxReference.AndrWebServiceSoap>, AsmxReference.AndrWebServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AndrWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AndrWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), AndrWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AndrWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AndrWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AndrWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AndrWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AndrWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync()
        {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string fname, string lname, string ph, string mail, string pass)
        {
            return base.Channel.RegisterAsync(fname, lname, ph, mail, pass);
        }
        
        public System.Threading.Tasks.Task<AsmxReference.Result> LoginAsync(string uname, string pass, string role)
        {
            return base.Channel.LoginAsync(uname, pass, role);
        }
        
        public System.Threading.Tasks.Task<string> SpecialistRegisterAsync(string fname, string lname, string ph, string center, string mail, string pass)
        {
            return base.Channel.SpecialistRegisterAsync(fname, lname, ph, center, mail, pass);
        }
        
        public System.Threading.Tasks.Task<string> AddStudentAsync(string fname, string lname, string gender, string pemail, System.DateTime dob, string cntr, string spFname, string spLname)
        {
            return base.Channel.AddStudentAsync(fname, lname, gender, pemail, dob, cntr, spFname, spLname);
        }
        
        public System.Threading.Tasks.Task<string> AdminRegiserAsync(string name, string email, string password, string center)
        {
            return base.Channel.AdminRegiserAsync(name, email, password, center);
        }
        
        public System.Threading.Tasks.Task<AsmxReference.Result> SaveGameStateAsync(string fn, string ln, string lvlid, int scr, System.DateTime t, int atmp, string parent)
        {
            return base.Channel.SaveGameStateAsync(fn, ln, lvlid, scr, t, atmp, parent);
        }
        
        public System.Threading.Tasks.Task<string[]> GetCentersAsync(string city)
        {
            return base.Channel.GetCentersAsync(city);
        }
        
        public System.Threading.Tasks.Task<string[]> GetUnConfirmedSpecAsync()
        {
            return base.Channel.GetUnConfirmedSpecAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetStudentsAsync(string email, string role, bool conf)
        {
            return base.Channel.GetStudentsAsync(email, role, conf);
        }
        
        public System.Threading.Tasks.Task<string[]> GetCitiesAsync()
        {
            return base.Channel.GetCitiesAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetLvlsAsync()
        {
            return base.Channel.GetLvlsAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetSpecialistsAsync(string center)
        {
            return base.Channel.GetSpecialistsAsync(center);
        }
        
        public System.Threading.Tasks.Task<string[]> AdminSpecialistsAsync(string email, bool conf)
        {
            return base.Channel.AdminSpecialistsAsync(email, conf);
        }
        
        public System.Threading.Tasks.Task<AsmxReference.Result> DeleteStudentAsync(string fname, string lname, string parent)
        {
            return base.Channel.DeleteStudentAsync(fname, lname, parent);
        }
        
        public System.Threading.Tasks.Task<string> GetParentEmailAsync(int id, string specEmail)
        {
            return base.Channel.GetParentEmailAsync(id, specEmail);
        }
        
        public System.Threading.Tasks.Task<string> GetAdminEmailAsync(string center)
        {
            return base.Channel.GetAdminEmailAsync(center);
        }
        
        public System.Threading.Tasks.Task<string> GetParentNumAsync(int id, string specEmail)
        {
            return base.Channel.GetParentNumAsync(id, specEmail);
        }
        
        public System.Threading.Tasks.Task<string> GetPassAsync(string email, string role)
        {
            return base.Channel.GetPassAsync(email, role);
        }
        
        public System.Threading.Tasks.Task<AsmxReference.Result> EmailIsExistsAsync(string email, string role)
        {
            return base.Channel.EmailIsExistsAsync(email, role);
        }
        
        public System.Threading.Tasks.Task<AsmxReference.GameState> GetStudentInfoAsync(int id, string specialist, string lvl)
        {
            return base.Channel.GetStudentInfoAsync(id, specialist, lvl);
        }
        
        public System.Threading.Tasks.Task<AsmxReference.Result> UpdateStudentfnameAsync(int id, string value)
        {
            return base.Channel.UpdateStudentfnameAsync(id, value);
        }
        
        public System.Threading.Tasks.Task<AsmxReference.Result> UpdateStudentLnameAsync(int id, string value)
        {
            return base.Channel.UpdateStudentLnameAsync(id, value);
        }
        
        public System.Threading.Tasks.Task<AsmxReference.Result> RandomStringAsync(int length, string center)
        {
            return base.Channel.RandomStringAsync(length, center);
        }
        
        public System.Threading.Tasks.Task<AsmxReference.Result> ConfirmStudentAsync(int id, bool conf)
        {
            return base.Channel.ConfirmStudentAsync(id, conf);
        }
        
        public System.Threading.Tasks.Task<AsmxReference.Result> ConfirmSpecialistAsync(string email, bool conf)
        {
            return base.Channel.ConfirmSpecialistAsync(email, conf);
        }
        
        public System.Threading.Tasks.Task<AsmxReference.Student> AdminStudentInfoAsync(int id, string email)
        {
            return base.Channel.AdminStudentInfoAsync(id, email);
        }
        
        public System.Threading.Tasks.Task<AsmxReference.Specialist> AdminSpecialisttInfoAsync(string email, string fn, string ln)
        {
            return base.Channel.AdminSpecialisttInfoAsync(email, fn, ln);
        }
        
        public System.Threading.Tasks.Task<string> GetFirstnameAsync(string item)
        {
            return base.Channel.GetFirstnameAsync(item);
        }
        
        public System.Threading.Tasks.Task<string> GetLastNameAsync(string item)
        {
            return base.Channel.GetLastNameAsync(item);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AndrWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AndrWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AndrWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://asmxwebservice.us-east-1.elasticbeanstalk.com/AndrWebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AndrWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://asmxwebservice.us-east-1.elasticbeanstalk.com/AndrWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AndrWebServiceSoap,
            
            AndrWebServiceSoap12,
        }
    }
}
