//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myCloudGamingReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(myCloudGamingReference.Admin))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(myCloudGamingReference.Center))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(myCloudGamingReference.Parent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(myCloudGamingReference.Student))]
    public partial class City : object
    {
        
        private string City_nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City_name
        {
            get
            {
                return this.City_nameField;
            }
            set
            {
                this.City_nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(myCloudGamingReference.Center))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(myCloudGamingReference.Parent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(myCloudGamingReference.Student))]
    public partial class Admin : myCloudGamingReference.City
    {
        
        private string AdmnEmailField;
        
        private string AdmnNameField;
        
        private string AdmnPasswordField;
        
        private string admnEmail1Field;
        
        private string admnName1Field;
        
        private string admnPassword1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdmnEmail
        {
            get
            {
                return this.AdmnEmailField;
            }
            set
            {
                this.AdmnEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdmnName
        {
            get
            {
                return this.AdmnNameField;
            }
            set
            {
                this.AdmnNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdmnPassword
        {
            get
            {
                return this.AdmnPasswordField;
            }
            set
            {
                this.AdmnPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="admnEmail")]
        public string admnEmail1
        {
            get
            {
                return this.admnEmail1Field;
            }
            set
            {
                this.admnEmail1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="admnName")]
        public string admnName1
        {
            get
            {
                return this.admnName1Field;
            }
            set
            {
                this.admnName1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="admnPassword")]
        public string admnPassword1
        {
            get
            {
                return this.admnPassword1Field;
            }
            set
            {
                this.admnPassword1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Center", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(myCloudGamingReference.Parent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(myCloudGamingReference.Student))]
    public partial class Center : myCloudGamingReference.Admin
    {
        
        private string Center_nameField;
        
        private string center_name1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Center_name
        {
            get
            {
                return this.Center_nameField;
            }
            set
            {
                this.Center_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="center_name")]
        public string center_name1
        {
            get
            {
                return this.center_name1Field;
            }
            set
            {
                this.center_name1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parent", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(myCloudGamingReference.Student))]
    public partial class Parent : myCloudGamingReference.Center
    {
        
        private string First_nameField;
        
        private string Last_nameField;
        
        private string ParentEmailField;
        
        private string ParentPasswordField;
        
        private string ParentPhoneField;
        
        private string parent_passField;
        
        private string parent_phoneField;
        
        private string pemailField;
        
        private string pfirstNameField;
        
        private string plastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_name
        {
            get
            {
                return this.First_nameField;
            }
            set
            {
                this.First_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_name
        {
            get
            {
                return this.Last_nameField;
            }
            set
            {
                this.Last_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentEmail
        {
            get
            {
                return this.ParentEmailField;
            }
            set
            {
                this.ParentEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentPassword
        {
            get
            {
                return this.ParentPasswordField;
            }
            set
            {
                this.ParentPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentPhone
        {
            get
            {
                return this.ParentPhoneField;
            }
            set
            {
                this.ParentPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parent_pass
        {
            get
            {
                return this.parent_passField;
            }
            set
            {
                this.parent_passField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parent_phone
        {
            get
            {
                return this.parent_phoneField;
            }
            set
            {
                this.parent_phoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pemail
        {
            get
            {
                return this.pemailField;
            }
            set
            {
                this.pemailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pfirstName
        {
            get
            {
                return this.pfirstNameField;
            }
            set
            {
                this.pfirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string plastName
        {
            get
            {
                return this.plastNameField;
            }
            set
            {
                this.plastNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    public partial class Student : myCloudGamingReference.Parent
    {
        
        private int AgeField;
        
        private System.DateTime DOBField;
        
        private string GenderField;
        
        private int IDField;
        
        private string ParentField;
        
        private string ResultField;
        
        private string SpecialistField;
        
        private string SpecialistNameField;
        
        private string StudntFirst_nameField;
        
        private string StudntLast_nameField;
        
        private int age1Field;
        
        private System.DateTime dob1Field;
        
        private string gndrField;
        
        private int id1Field;
        
        private string parent1Field;
        
        private string resltField;
        
        private string specialist1Field;
        
        private string spfnameField;
        
        private string stfnameField;
        
        private string stlnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DOB
        {
            get
            {
                return this.DOBField;
            }
            set
            {
                this.DOBField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parent
        {
            get
            {
                return this.ParentField;
            }
            set
            {
                this.ParentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Specialist
        {
            get
            {
                return this.SpecialistField;
            }
            set
            {
                this.SpecialistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialistName
        {
            get
            {
                return this.SpecialistNameField;
            }
            set
            {
                this.SpecialistNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudntFirst_name
        {
            get
            {
                return this.StudntFirst_nameField;
            }
            set
            {
                this.StudntFirst_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudntLast_name
        {
            get
            {
                return this.StudntLast_nameField;
            }
            set
            {
                this.StudntLast_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="age")]
        public int age1
        {
            get
            {
                return this.age1Field;
            }
            set
            {
                this.age1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="dob")]
        public System.DateTime dob1
        {
            get
            {
                return this.dob1Field;
            }
            set
            {
                this.dob1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gndr
        {
            get
            {
                return this.gndrField;
            }
            set
            {
                this.gndrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="id")]
        public int id1
        {
            get
            {
                return this.id1Field;
            }
            set
            {
                this.id1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="parent")]
        public string parent1
        {
            get
            {
                return this.parent1Field;
            }
            set
            {
                this.parent1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reslt
        {
            get
            {
                return this.resltField;
            }
            set
            {
                this.resltField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="specialist")]
        public string specialist1
        {
            get
            {
                return this.specialist1Field;
            }
            set
            {
                this.specialist1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spfname
        {
            get
            {
                return this.spfnameField;
            }
            set
            {
                this.spfnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stfname
        {
            get
            {
                return this.stfnameField;
            }
            set
            {
                this.stfnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stlname
        {
            get
            {
                return this.stlnameField;
            }
            set
            {
                this.stlnameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="myCloudGamingReference.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentInfoList", ReplyAction="http://tempuri.org/IService1/GetStudentInfoListResponse")]
        System.Threading.Tasks.Task<string[]> GetStudentInfoListAsync(int id, string specialist, string lvl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(string fname, string lname, string ph, string mail, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string uname, string pass, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SpecialistRegister", ReplyAction="http://tempuri.org/IService1/SpecialistRegisterResponse")]
        System.Threading.Tasks.Task<string> SpecialistRegisterAsync(string fname, string lname, string ph, string center, string mail, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStudent", ReplyAction="http://tempuri.org/IService1/AddStudentResponse")]
        System.Threading.Tasks.Task<string> AddStudentAsync(string fname, string lname, string gender, string pemail, System.DateTime dob, string cntr, string spFname, string spLname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AdminRegiser", ReplyAction="http://tempuri.org/IService1/AdminRegiserResponse")]
        System.Threading.Tasks.Task<string> AdminRegiserAsync(string name, string email, string password, string center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveGameState", ReplyAction="http://tempuri.org/IService1/SaveGameStateResponse")]
        System.Threading.Tasks.Task<bool> SaveGameStateAsync(int id, string lvlid, int scr, int t, string parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCities", ReplyAction="http://tempuri.org/IService1/GetCitiesResponse")]
        System.Threading.Tasks.Task<string[]> GetCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCenters", ReplyAction="http://tempuri.org/IService1/GetCentersResponse")]
        System.Threading.Tasks.Task<string[]> GetCentersAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSpecialists", ReplyAction="http://tempuri.org/IService1/GetSpecialistsResponse")]
        System.Threading.Tasks.Task<string[]> GetSpecialistsAsync(string center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AdminSpecialists", ReplyAction="http://tempuri.org/IService1/AdminSpecialistsResponse")]
        System.Threading.Tasks.Task<string[]> AdminSpecialistsAsync(string email, bool conf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUnConfirmedSpec", ReplyAction="http://tempuri.org/IService1/GetUnConfirmedSpecResponse")]
        System.Threading.Tasks.Task<string[]> GetUnConfirmedSpecAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStudent", ReplyAction="http://tempuri.org/IService1/DeleteStudentResponse")]
        System.Threading.Tasks.Task<bool> DeleteStudentAsync(string fname, string lname, string parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdminEmail", ReplyAction="http://tempuri.org/IService1/GetAdminEmailResponse")]
        System.Threading.Tasks.Task<string> GetAdminEmailAsync(string center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetParentEmail", ReplyAction="http://tempuri.org/IService1/GetParentEmailResponse")]
        System.Threading.Tasks.Task<string> GetParentEmailAsync(int id, string specEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetParentNum", ReplyAction="http://tempuri.org/IService1/GetParentNumResponse")]
        System.Threading.Tasks.Task<string> GetParentNumAsync(int id, string specEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPass", ReplyAction="http://tempuri.org/IService1/GetPassResponse")]
        System.Threading.Tasks.Task<string> GetPassAsync(string email, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EmailIsExists", ReplyAction="http://tempuri.org/IService1/EmailIsExistsResponse")]
        System.Threading.Tasks.Task<bool> EmailIsExistsAsync(string email, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSpecialistsStudents", ReplyAction="http://tempuri.org/IService1/GetSpecialistsStudentsResponse")]
        System.Threading.Tasks.Task<string[]> GetSpecialistsStudentsAsync(string specialist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLvls", ReplyAction="http://tempuri.org/IService1/GetLvlsResponse")]
        System.Threading.Tasks.Task<string[]> GetLvlsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudents", ReplyAction="http://tempuri.org/IService1/GetStudentsResponse")]
        System.Threading.Tasks.Task<string[]> GetStudentsAsync(string email, string role, bool conf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStudentfname", ReplyAction="http://tempuri.org/IService1/UpdateStudentfnameResponse")]
        System.Threading.Tasks.Task<bool> UpdateStudentfnameAsync(int id, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStudentLname", ReplyAction="http://tempuri.org/IService1/UpdateStudentLnameResponse")]
        System.Threading.Tasks.Task<bool> UpdateStudentLnameAsync(int id, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStudentDoB", ReplyAction="http://tempuri.org/IService1/UpdateStudentDoBResponse")]
        System.Threading.Tasks.Task<bool> UpdateStudentDoBAsync(int id, System.DateTime dob);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStudentSpec", ReplyAction="http://tempuri.org/IService1/UpdateStudentSpecResponse")]
        System.Threading.Tasks.Task<string> UpdateStudentSpecAsync(int id, string sfn, string sln, string center, string parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentOld", ReplyAction="http://tempuri.org/IService1/GetStudentOldResponse")]
        System.Threading.Tasks.Task<myCloudGamingReference.Student> GetStudentOldAsync(string fn, string ln, string parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RandomString", ReplyAction="http://tempuri.org/IService1/RandomStringResponse")]
        System.Threading.Tasks.Task<bool> RandomStringAsync(int length, string center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AdminConfirmation", ReplyAction="http://tempuri.org/IService1/AdminConfirmationResponse")]
        System.Threading.Tasks.Task<bool> AdminConfirmationAsync(string center, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConfirmStudent", ReplyAction="http://tempuri.org/IService1/ConfirmStudentResponse")]
        System.Threading.Tasks.Task<bool> ConfirmStudentAsync(int id, bool conf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConfirmSpecialist", ReplyAction="http://tempuri.org/IService1/ConfirmSpecialistResponse")]
        System.Threading.Tasks.Task<bool> ConfirmSpecialistAsync(string email, bool conf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AdminStudentInfo", ReplyAction="http://tempuri.org/IService1/AdminStudentInfoResponse")]
        System.Threading.Tasks.Task<string[]> AdminStudentInfoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AdminSpecialisttInfo", ReplyAction="http://tempuri.org/IService1/AdminSpecialisttInfoResponse")]
        System.Threading.Tasks.Task<string[]> AdminSpecialisttInfoAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFirstname", ReplyAction="http://tempuri.org/IService1/GetFirstnameResponse")]
        System.Threading.Tasks.Task<string> GetFirstnameAsync(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLastName", ReplyAction="http://tempuri.org/IService1/GetLastNameResponse")]
        System.Threading.Tasks.Task<string> GetLastNameAsync(string item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IService1Channel : myCloudGamingReference.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<myCloudGamingReference.IService1>, myCloudGamingReference.IService1
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string[]> GetStudentInfoListAsync(int id, string specialist, string lvl)
        {
            return base.Channel.GetStudentInfoListAsync(id, specialist, lvl);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string fname, string lname, string ph, string mail, string pass)
        {
            return base.Channel.RegisterAsync(fname, lname, ph, mail, pass);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string uname, string pass, string role)
        {
            return base.Channel.LoginAsync(uname, pass, role);
        }
        
        public System.Threading.Tasks.Task<string> SpecialistRegisterAsync(string fname, string lname, string ph, string center, string mail, string pass)
        {
            return base.Channel.SpecialistRegisterAsync(fname, lname, ph, center, mail, pass);
        }
        
        public System.Threading.Tasks.Task<string> AddStudentAsync(string fname, string lname, string gender, string pemail, System.DateTime dob, string cntr, string spFname, string spLname)
        {
            return base.Channel.AddStudentAsync(fname, lname, gender, pemail, dob, cntr, spFname, spLname);
        }
        
        public System.Threading.Tasks.Task<string> AdminRegiserAsync(string name, string email, string password, string center)
        {
            return base.Channel.AdminRegiserAsync(name, email, password, center);
        }
        
        public System.Threading.Tasks.Task<bool> SaveGameStateAsync(int id, string lvlid, int scr, int t, string parent)
        {
            return base.Channel.SaveGameStateAsync(id, lvlid, scr, t, parent);
        }
        
        public System.Threading.Tasks.Task<string[]> GetCitiesAsync()
        {
            return base.Channel.GetCitiesAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCentersAsync(string city)
        {
            return base.Channel.GetCentersAsync(city);
        }
        
        public System.Threading.Tasks.Task<string[]> GetSpecialistsAsync(string center)
        {
            return base.Channel.GetSpecialistsAsync(center);
        }
        
        public System.Threading.Tasks.Task<string[]> AdminSpecialistsAsync(string email, bool conf)
        {
            return base.Channel.AdminSpecialistsAsync(email, conf);
        }
        
        public System.Threading.Tasks.Task<string[]> GetUnConfirmedSpecAsync()
        {
            return base.Channel.GetUnConfirmedSpecAsync();
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStudentAsync(string fname, string lname, string parent)
        {
            return base.Channel.DeleteStudentAsync(fname, lname, parent);
        }
        
        public System.Threading.Tasks.Task<string> GetAdminEmailAsync(string center)
        {
            return base.Channel.GetAdminEmailAsync(center);
        }
        
        public System.Threading.Tasks.Task<string> GetParentEmailAsync(int id, string specEmail)
        {
            return base.Channel.GetParentEmailAsync(id, specEmail);
        }
        
        public System.Threading.Tasks.Task<string> GetParentNumAsync(int id, string specEmail)
        {
            return base.Channel.GetParentNumAsync(id, specEmail);
        }
        
        public System.Threading.Tasks.Task<string> GetPassAsync(string email, string role)
        {
            return base.Channel.GetPassAsync(email, role);
        }
        
        public System.Threading.Tasks.Task<bool> EmailIsExistsAsync(string email, string role)
        {
            return base.Channel.EmailIsExistsAsync(email, role);
        }
        
        public System.Threading.Tasks.Task<string[]> GetSpecialistsStudentsAsync(string specialist)
        {
            return base.Channel.GetSpecialistsStudentsAsync(specialist);
        }
        
        public System.Threading.Tasks.Task<string[]> GetLvlsAsync()
        {
            return base.Channel.GetLvlsAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetStudentsAsync(string email, string role, bool conf)
        {
            return base.Channel.GetStudentsAsync(email, role, conf);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStudentfnameAsync(int id, string value)
        {
            return base.Channel.UpdateStudentfnameAsync(id, value);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStudentLnameAsync(int id, string value)
        {
            return base.Channel.UpdateStudentLnameAsync(id, value);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStudentDoBAsync(int id, System.DateTime dob)
        {
            return base.Channel.UpdateStudentDoBAsync(id, dob);
        }
        
        public System.Threading.Tasks.Task<string> UpdateStudentSpecAsync(int id, string sfn, string sln, string center, string parent)
        {
            return base.Channel.UpdateStudentSpecAsync(id, sfn, sln, center, parent);
        }
        
        public System.Threading.Tasks.Task<myCloudGamingReference.Student> GetStudentOldAsync(string fn, string ln, string parent)
        {
            return base.Channel.GetStudentOldAsync(fn, ln, parent);
        }
        
        public System.Threading.Tasks.Task<bool> RandomStringAsync(int length, string center)
        {
            return base.Channel.RandomStringAsync(length, center);
        }
        
        public System.Threading.Tasks.Task<bool> AdminConfirmationAsync(string center, string code)
        {
            return base.Channel.AdminConfirmationAsync(center, code);
        }
        
        public System.Threading.Tasks.Task<bool> ConfirmStudentAsync(int id, bool conf)
        {
            return base.Channel.ConfirmStudentAsync(id, conf);
        }
        
        public System.Threading.Tasks.Task<bool> ConfirmSpecialistAsync(string email, bool conf)
        {
            return base.Channel.ConfirmSpecialistAsync(email, conf);
        }
        
        public System.Threading.Tasks.Task<string[]> AdminStudentInfoAsync(int id)
        {
            return base.Channel.AdminStudentInfoAsync(id);
        }
        
        public System.Threading.Tasks.Task<string[]> AdminSpecialisttInfoAsync(string email)
        {
            return base.Channel.AdminSpecialisttInfoAsync(email);
        }
        
        public System.Threading.Tasks.Task<string> GetFirstnameAsync(string item)
        {
            return base.Channel.GetFirstnameAsync(item);
        }
        
        public System.Threading.Tasks.Task<string> GetLastNameAsync(string item)
        {
            return base.Channel.GetLastNameAsync(item);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://mycloudgaming.us-east-1.elasticbeanstalk.com/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
